name: Next.js CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Type check
      run: pnpm type-check
      
    - name: Build application
      run: pnpm build
      
    - name: Run tests
      run: pnpm test --passWithNoTests
      
    - name: Lint code
      run: pnpm lint --if-present
